config/routes.rb
Rails.application.routes.draw do
  devise_scope :store do
    authenticated :store do
      root :to => 'stores#index', as: :authenticated_root
    end
    unauthenticated :store do
      root :to => 'users#index', as: :unauthenticated_root
    end
  end

  devise_for :stores
  resources :stores, only:[:index, :show]
  resources :products
  resources :order_slips, only:[:index, :update]
  resources :number_purchases, only:[:index, :show]
  resources :users do
    collection do
      get :edit_search
    end
  end
  resources :user_info, only:[:index]

  post '/callback' => 'linebot#callback'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/store.rb
class Store < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader
  has_many :products, dependent: :destroy
  has_many :relationship, dependent: :destroy
  has_many :users, through: :relationship

  validates :name, presence: true, length: { maximum: 30 }
  validates :address, presence: true
  validates :telephone, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :access, presence: true
  validates :image, presence: true

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show]
  before_action :authenticate_store!

  def index
    @store = Store.find(current_store.id)
  end

  def show; end

  private

  def set_store
    @store = Store.find(params[:id])
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/index.html.erb
  <h1 class='index_content'>store_indexメニュー画面</h1>
  <!-- TODO: store_indexには全店舗の商品を表示することで、自分の店の参考にできるとか？ -->

app/views/stores/show.html.erb
<div class="card form_frame store_form">
  <div class="card-body login-card-body">
    <table>
      <tr>
        <th><%= t('activerecord.attributes.store.name') %></th>
        <td><%= @store.name %></td>
      </tr>
      <tr>
        <th><%= t('activerecord.attributes.store.address') %></th>
        <td><%= @store.address %></td>
      </tr>
      <tr>
        <th><%= t('activerecord.attributes.store.email') %></th>
        <td><%= @store.email %></td>
      </tr>
      <tr>
        <th><%= t('activerecord.attributes.store.telephone') %></th>
        <td><%= @store.telephone %></td>
      </tr>
      <tr>
        <th>営業時間</th>
        <td>
          <% if (@store.start_time.hour - 12) < 0 %>
            午前
          <% else %>
            午後
          <% end %>
          <%= @store.start_time.hour %>:
          <!-- TODO: 13:00や18:30といった表示にしたい -->
          <%= @store.start_time.min %>
          〜
          <% if (@store.end_time.hour - 12) < 0 %>
            午前
          <% else %>
            午後
          <% end %>
          <%= @store.end_time.hour %>:
          <%= @store.end_time.min %>
        </td>
      </tr>
      <tr>
        <th><%= t('activerecord.attributes.store.access') %></th>
        <td><%= @store.access %></td>
      </tr>
        <tr>
        <th><%= t('activerecord.attributes.store.image') %></th>
        <td><%= image_tag(@store.image.url, :size => "400x300") %></td>
      </tr>
    </table>

    <%= link_to '編集', edit_store_registration_path(@store.id), class: 'btn btn-primary btn-sm'%>
  </div>
</div>