config/routes.rb
Rails.application.routes.draw do
  devise_scope :store do
    authenticated :store do
      root :to => 'stores#index', as: :authenticated_root
    end
    unauthenticated :store do
      root :to => 'users#index', as: :unauthenticated_root
    end
  end

  devise_for :stores
  resources :stores, only:[:index, :show]
  resources :products
  resources :order_slips, only:[:index, :update]
  resources :number_purchases, only:[:index, :show]
  resources :users do
    collection do
      get :edit_search
    end
  end
  resources :user_info, only:[:index]

  post '/callback' => 'linebot#callback'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :number_purchases, dependent: :destroy
  has_many :relationship, dependent: :destroy
  has_many :stores, through: :relationship

  validates :name, presence: true
  validates :address, presence: true
  validates :email, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_store!, only: [:index]
  before_action :set_user, only: [:update]
  # newとeditはLINEから送られてきた時だけアクセス許可する。

  def index; end

  def new
    @user = User.new
    # @user.line_id = @user_id
  end
  
  def create
    # TODO: 同時にcreateされた時にずれが生じる可能性がある
    if params[:line_id].present?
      if User.find_by(line_id: params[:line_id])
        puts "既に登録されているLINE_IDです。"
      else
        user = User.new
        user.name = "nil"
        user.email = "nil"
        user.address = "nil"
        user.line_id = params[:line_id]
        if user.save
          puts "line_id登録成功"
        else
          puts "line_id登録失敗"
        end
      end
    else
      user = User.last
      user_not_line_id = User.new(user_params)
      if user.name == "nil" && user.email == "nil" && user.address == "nil" && user.line_id.present?
        user.name = user_not_line_id.name
        user.age = user_not_line_id.age
        user.sex = user_not_line_id.sex
        user.profession = user_not_line_id.profession
        user.email = user_not_line_id.email
        user.address = user_not_line_id.address
        if user.save
          puts "user登録成功"
        else
          puts "user登録失敗"
          @user = user
          user.destroy
          render :new
        end
      else
        puts "既に登録されているLINE_IDでuser登録処理を行おうとしています"
      end
    end
  end

  def edit
    @user = User.find_by(line_id: @line_id)
    render :edit
  end

  def update

  end

  def edit_search
    if params[:line_id].present?
      @line_id = params[:line_id]
      edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :age, :sex, :profession, :email, :address)
  end

  def recieve
    body = request.body.read
    events = client.parse_events_from(body)
    events.each do |event|
      @user_id = event['source']['userId']
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>'ono pan</title>
</head>

<body>
  <%= @user.line_id %>
  <script src="https://d.line-scdn.net/liff/1.0/sdk.js"></script>
</body>

app/views/users/edit_search.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>'ono pan</title>
</head>

<body>
  <input type="submit" value="今すぐ編集する" class='btn btn-primary btn-sm user_profile_edit'>
  <script src="https://d.line-scdn.net/liff/1.0/sdk.js"></script>
</body>

app/views/users/index.html.erb
<strong>LINE Bot ID : @287cbvsm</strong>
<p><a href="http://nav.cx/4XnXhNs"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="36" border="0"></a></p>
<hr>
<p>パン屋さんはこちらからログインまたはサインアップして下さい</p>
<%= link_to 'ログイン', new_store_session_path %> | 
<%= link_to 'サインアップ', new_store_registration_path %>

app/views/users/new.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>'ono pan</title>
</head>

<body>
  <h3>プロフィール</h3>
    <% if @user.errors.any? %>
      <div id='error_explanation' class='alert alert alert-danger'>
        <h2><%= pluralize(@user.errors.count, 'error') %></h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with(model: @user, local: true) do |f| %>
      <table>
        <tr><td><%= f.label :name %></td></tr>
        <tr><td><%= f.text_field :name %></td></tr>
        <tr><td><%= f.label :age %></td></tr>
        <td><%= f.number_field :age %></td></tr>
        <tr><td><%= f.label :sex %></td></tr>
        <tr><td>
          <label><%= f.radio_button :sex, "男" %>男</label>
          <label><%= f.radio_button :sex, "女" %>女</label>
        </td></tr>
        <tr><td><%= f.label :profession %></td></tr>
        <tr><td>
          <%= f.select :profession, [["社会人", "社会人"], ["学生", "学生"], ["主婦", "主婦"]] %>
        </td></tr>
        <tr><td><%= f.label :email %></td></tr>
        <tr><td><%= f.text_field :email %></td></tr>
        <tr><td><%= f.label :address %></td></tr>
        <tr><td><%= f.text_field :address %></td></tr>
      </table>
      <div class='actions'>
        <hr>
        <%= f.submit class: 'btn btn-primary btn-sm user_profile_create' %>
      </div>
    <% end %>
  <script src="https://d.line-scdn.net/liff/1.0/sdk.js"></script>
</body>