config/routes.rb
Rails.application.routes.draw do
  devise_scope :store do
    authenticated :store do
      root :to => 'stores#index', as: :authenticated_root
    end
    unauthenticated :store do
      root :to => 'users#index', as: :unauthenticated_root
    end
  end

  devise_for :stores
  resources :stores, only:[:index, :show]
  resources :products
  resources :order_slips, only:[:index, :update]
  resources :number_purchases, only:[:index, :show]
  resources :users do
    collection do
      get :edit_search
    end
  end
  resources :user_info, only:[:index]

  post '/callback' => 'linebot#callback'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  has_many :product_images, dependent: :destroy
  has_many :number_purchases, dependent: :destroy
  accepts_nested_attributes_for :product_images, allow_destroy: true

  validates :name, presence: true
  validates :number, presence: true
  validates :price, presence: true
  validates :content, presence: true
  validates :preservation, presence: true
  validates :how_to_eat, presence: true
  validates :expiration, presence: true
  validates :shipping, presence: true
end

app/controllers/products_controller.rb
require 'line/bot'

class ProductsController < ApplicationController
  # before_action :set_store
  before_action :authenticate_store!
  before_action :set_product, only: [:edit, :update, :destroy]

  def index
    @products = Product.where(store_id: current_store.id).order(created_at: :asc)
  end

  def new
    @product = Product.new
    @product.product_images.build
  end

  def create
    @product = Product.new(product_params)
    @product.store_id = current_store.id
    if @product.save
      client
      users_id = User.all.select(:line_id)
      users_id.each do |user_id|
        client.push_message(user_id.line_id, product_message)
      end
      redirect_to products_path, notice: '新しい商品を作成しました'
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @product.update(product_params)
      client
      users_id = User.all.select(:line_id)
      users_id.each do |user_id|
        client.push_message(user_id.line_id, product_message)
      end
      redirect_to products_path, notice: '商品情報を編集しました'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice: '商品を削除しました'

  end

  private

  # def set_store
  #   @store = Store.find(current_store.id)
  # end

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(
      :name,
      :number,
      :price,
      :content,
      :preservation,
      :how_to_eat,
      :expiration,
      :shipping,
      :remarks,
      :store_id,
      product_images_attributes: %i[id image product_id],
    )
  end

  def product_message
    {
      "type": "flex",
      "altText": "Flex Message",
      "contents": {
        "type": "bubble",
        "hero": {
          "type": "image",
          # TODO: パン商品の画像のURLをここに貼る。ローカルじゃだめ？@product.product_images.first.image.url
          "url": "https://cdn.pixabay.com/photo/2019/05/09/20/57/bread-4192142_960_720.jpg",
          "size": "full",
          "aspectRatio": "20:13",
          "aspectMode": "cover",
          "action": {
            "type": "uri",
            "label": "Action",
            "uri": "https://linecorp.com"
          }
        },
        "body": {
          "type": "box",
          "layout": "vertical",
          "spacing": "md",
          "action": {
            "type": "uri",
            "label": "Action",
            "uri": "https://linecorp.com"
          },
          "contents": [
            {
              "type": "text",
              "text": "#{@product.store.name}",
              "size": "xl",
              "weight": "bold"
            },
            {
              "type": "box",
              "layout": "vertical",
              "spacing": "sm",
              "contents": [
                {
                  "type": "box",
                  "layout": "vertical",
                  "spacing": "sm",
                  "margin": "lg",
                  "contents": [
                    {
                      "type": "box",
                      "layout": "baseline",
                      "spacing": "sm",
                      "contents": [
                        {
                          "type": "text",
                          "text": "#{t('activerecord.attributes.store.address')}",
                          "flex": 2,
                          "size": "sm",
                          "color": "#AAAAAA"
                        },
                        {
                          "type": "text",
                          "text": "#{@product.store.address}",
                          "flex": 5,
                          "size": "sm",
                          "color": "#666666",
                          "wrap": true
                        }
                      ]
                    },
                    # TODO: 評価入れたい
                    {
                      "type": "box",
                      "layout": "baseline",
                      "spacing": "sm",
                      "contents": [
                        {
                          "type": "text",
                          "text": "#{t('activerecord.attributes.product.name')}",
                          "flex": 2,
                          "size": "sm",
                          "color": "#AAAAAA"
                        },
                        {
                          "type": "text",
                          "text": "#{@product.name}",
                          "flex": 5,
                          "size": "sm",
                          "color": "#666666",
                          "wrap": true
                        }
                      ]
                    },
                    {
                      "type": "box",
                      "layout": "baseline",
                      "spacing": "sm",
                      "contents": [
                        {
                          "type": "text",
                          "text": "#{t('activerecord.attributes.product.price')}",
                          "flex": 2,
                          "size": "sm",
                          "color": "#AAAAAA"
                        },
                        {
                          "type": "text",
                          "text": "#{@product.price.to_s(:delimited)}円",
                          "flex": 5,
                          "size": "sm",
                          "color": "#666666",
                          "wrap": true
                        }
                      ]
                    },
                    {
                      "type": "box",
                      "layout": "baseline",
                      "spacing": "sm",
                      "contents": [
                        {
                          "type": "text",
                          "text": "#{t('activerecord.attributes.product.number')}",
                          "flex": 2,
                          "size": "sm",
                          "color": "#AAAAAA"
                        },
                        {
                          "type": "text",
                          "text": "#{@product.number.to_s(:delimited)}個",
                          "flex": 5,
                          "size": "sm",
                          "color": "#666666",
                          "wrap": true
                        }
                      ]
                    },
                    # TODO: 原材料
                    {
                      "type": "box",
                      "layout": "baseline",
                      "spacing": "sm",
                      "contents": [
                        {
                          "type": "text",
                          "text": "#{t('activerecord.attributes.product.expiration')}",
                          "flex": 2,
                          "size": "sm",
                          "color": "#AAAAAA"
                        },
                        {
                          "type": "text",
                          "text": "#{@product.expiration}",
                          "flex": 5,
                          "size": "sm",
                          "color": "#666666",
                          "wrap": true
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        "footer": {
          "type": "box",
          "layout": "vertical",
          "contents": [
            {
              "type": "spacer",
              "size": "xxl"
            },
            {
              "type": "button",
              "action": {
                "type": "message",
                "label": "購入",
                "text": "購入_#{@product.id}"
              },
              "color": "#905C44",
              "style": "primary"
            }
          ]
        }
      }
    }
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<div class='row product_form'>
  <div class='col-md-12'>
    <h1>商品編集フォーム</h1>
    <% if @product.errors.any? %>
      <div id='error_explanation' class='alert alert alert-danger'>
        <h2><%= pluralize(@product.errors.count, 'error') %></h2>
        <ul>
          <% @product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with(model: @product, local: true) do |f| %>
      <table>
        <tr class='field'>
          <th><%= f.label :name %></th>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr class='field'>
          <th><%= f.label :number %></th>
          <td><%= f.number_field :number %></td>
        </tr>
        <tr class='field'>
          <th><%= f.label :price %></th>
          <td><%= f.number_field :price %></td>
        </tr>
        <tr class='field'>
          <th><%= f.label :content %></th>
          <td><%= f.text_area :content %></td>
        </tr>
        <tr class='field'>
          <th><%= f.label :preservation %></th>
          <td><%= f.text_area :preservation %></td>
        </tr>
        <tr class='field'>
          <th><%= f.label :how_to_eat %></th>
          <td><%= f.text_area :how_to_eat %></td>
        </tr>
        <tr class='field'>
          <th><%= f.label :expiration %></th>
          <td><%= f.text_area :expiration %></td>
        </tr>
        <tr class='field'>
          <th><%= f.label :shipping %></th>
          <td><%= f.text_area :shipping %></td>
        </tr>
        <tr class='field'>
          <th><%= f.label :remarks %></th>
          <td><%= f.text_area :remarks %></td>
        </tr>
        <tr class='field'>
          <th><%= f.label :product, "商品画像" %></th>
          <%= f.fields_for :product_images do |p_image_form| %>
            <td>
              <% @product.product_images.each do |p_i| %>
                <%= image_tag(p_i.image.url) if p_i.image && p_i.image.url %>
              <% end %>
              <%= p_image_form.file_field :image %>
              <%= p_image_form.hidden_field :image_cache %>
            </td>
          <% end %>
        </tr>
      </table>
      <div class='actions'>
        <%= f.submit class: 'btn btn-primary btn-sm'%>
        <%= link_to '戻る', :back, class: 'btn btn-default btn-sm' %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<h1>商品管理画面</h1>
<p id="notice"><%= notice %></p>

<%= link_to '新しく商品を登録する', new_product_path, class: 'btn btn-primary btn-sm' %>
<div class='row screen_frame'>
  <% @products.each do |product| %>
    <div class='col-md-5 product_frame'>
      <table>
        <% product.product_images.each do |p_image| %>
          <tr>
            <th><%= t('activerecord.attributes.product_image.image') %></th>
            <td><%= image_tag(p_image.image.url, :size => "160x120") %></td>
          </tr>
        <% end %>
        <tr>
          <th><%= t('activerecord.attributes.product.name') %></th>
          <td><%= product.name %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.product.number') %></th>
          <td><%= product.number.to_s(:delimited) %>個</td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.product.price') %></th>
          <td><%= product.price.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.product.content') %></th>
          <td><%= product.content %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.product.preservation') %></th>
          <td><%= product.preservation %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.product.how_to_eat') %></th>
          <td><%= product.how_to_eat %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.product.expiration') %></th>
          <td><%= product.expiration %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.product.shipping') %></th>
          <td><%= product.shipping %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.product.remarks') %></th>
          <td><%= product.remarks %></td>
        </tr>
      </table>
      <%= link_to '編集', edit_product_path(product.id) %> | 
      <%= link_to '削除', product_path(product.id), method: :delete, data: { confirm: '本当に削除しますか？' } %>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<div class='row product_form'>
  <div class='col-md-12'>
    <h1>商品登録フォーム</h1>
    <% if @product.errors.any? %>
      <div id='error_explanation' class='alert alert alert-danger'>
        <h2><%= pluralize(@product.errors.count, 'error') %></h2>
        <ul>
          <% @product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with(model: @product, local: true) do |f| %>
      <table>
        <tr class='field'>
          <th><%= f.label :name %></th>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr class='field'>
          <th><%= f.label :number %></th>
          <td><%= f.number_field :number %></td>
        </tr>
        <tr class='field'>
          <th><%= f.label :price %></th>
          <td><%= f.number_field :price %></td>
        </tr>
        <!-- TODO: 原材料 -->
        <tr class='field'>
          <th><%= f.label :content %></th>
          <td><%= f.text_area :content %></td>
        </tr>
        <tr class='field'>
          <th><%= f.label :preservation %></th>
          <td><%= f.text_area :preservation %></td>
        </tr>
        <tr class='field'>
          <th><%= f.label :how_to_eat %></th>
          <td><%= f.text_area :how_to_eat %></td>
        </tr>
        <tr class='field'>
          <th><%= f.label :expiration %></th>
          <td><%= f.text_area :expiration %></td>
        </tr>
        <tr class='field'>
          <th><%= f.label :shipping %></th>
          <td><%= f.text_area :shipping %></td>
        </tr>
        <tr class='field'>
          <th><%= f.label :remarks %></th>
          <td><%= f.text_area :remarks %></td>
        </tr>
        <tr class='field'>
          <th><%= f.label :product, "商品画像" %></th>
          <%= f.fields_for :product_images do |p_image_form| %>
            <td>
              <% @product.product_images.each do |p_i| %>
                <%= image_tag(p_i.image.url) if p_i.image && p_i.image.url %>
              <% end %>
              <%= p_image_form.file_field :image %>
              <%= p_image_form.hidden_field :image_cache %>
            </td>
          <% end %>
        </tr>
      </table>
      <div class='actions'>
        <%= f.submit class: 'btn btn-primary btn-sm'%>
        <%= link_to '戻る', :back, class: 'btn btn-default btn-sm' %>
      </div>
    <% end %>
  </div>
</div>