config/routes.rb
Rails.application.routes.draw do
  devise_scope :store do
    authenticated :store do
      root :to => 'stores#index', as: :authenticated_root
    end
    unauthenticated :store do
      root :to => 'users#index', as: :unauthenticated_root
    end
  end

  devise_for :stores
  resources :stores, only:[:index, :show]
  resources :products
  resources :order_slips, only:[:index, :update]
  resources :number_purchases, only:[:index, :show]
  resources :users do
    collection do
      get :edit_search
    end
  end
  resources :user_info, only:[:index]

  post '/callback' => 'linebot#callback'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/allergy.rb
class Allergy < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/number_purchase.rb
class NumberPurchase < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  has_many :product_images, dependent: :destroy
  has_many :number_purchases, dependent: :destroy
  accepts_nested_attributes_for :product_images, allow_destroy: true

  validates :name, presence: true
  validates :number, presence: true
  validates :price, presence: true
  validates :content, presence: true
  validates :preservation, presence: true
  validates :how_to_eat, presence: true
  validates :expiration, presence: true
  validates :shipping, presence: true
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product

  mount_uploader :image, ImageUploader

  validates :image, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader
  has_many :products, dependent: :destroy
  has_many :relationship, dependent: :destroy
  has_many :users, through: :relationship

  validates :name, presence: true, length: { maximum: 30 }
  validates :address, presence: true
  validates :telephone, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :access, presence: true
  validates :image, presence: true

end

app/models/used_ingredient.rb
class UsedIngredient < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :number_purchases, dependent: :destroy
  has_many :relationship, dependent: :destroy
  has_many :stores, through: :relationship

  validates :name, presence: true
  validates :address, presence: true
  validates :email, presence: true
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show]
  before_action :authenticate_store!

  def index
    @store = Store.find(current_store.id)
  end

  def show; end

  private

  def set_store
    @store = Store.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_store!, only: [:index]
  before_action :set_user, only: [:update]
  # newとeditはLINEから送られてきた時だけアクセス許可する。

  def index; end

  def new
    @user = User.new
    # @user.line_id = @user_id
  end
  
  def create
    # TODO: 同時にcreateされた時にずれが生じる可能性がある
    if params[:line_id].present?
      if User.find_by(line_id: params[:line_id])
        puts "既に登録されているLINE_IDです。"
      else
        user = User.new
        user.name = "nil"
        user.email = "nil"
        user.address = "nil"
        user.line_id = params[:line_id]
        if user.save
          puts "line_id登録成功"
        else
          puts "line_id登録失敗"
        end
      end
    else
      user = User.last
      user_not_line_id = User.new(user_params)
      if user.name == "nil" && user.email == "nil" && user.address == "nil" && user.line_id.present?
        user.name = user_not_line_id.name
        user.age = user_not_line_id.age
        user.sex = user_not_line_id.sex
        user.profession = user_not_line_id.profession
        user.email = user_not_line_id.email
        user.address = user_not_line_id.address
        if user.save
          puts "user登録成功"
        else
          puts "user登録失敗"
          @user = user
          user.destroy
          render :new
        end
      else
        puts "既に登録されているLINE_IDでuser登録処理を行おうとしています"
      end
    end
  end

  def edit
    @user = User.find_by(line_id: @line_id)
    render :edit
  end

  def update

  end

  def edit_search
    if params[:line_id].present?
      @line_id = params[:line_id]
      edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :age, :sex, :profession, :email, :address)
  end

  def recieve
    body = request.body.read
    events = client.parse_events_from(body)
    events.each do |event|
      @user_id = event['source']['userId']
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/linebot_helper.rb
module LinebotHelper
end

app/helpers/order_slips_helper.rb
module OrderSlipsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/user_info_helper.rb
module UserInfoHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>'Onopan</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://cdn.lr-ingest.io/LogRocket.min.js" crossorigin="anonymous"></script>
    <script>window.LogRocket && window.LogRocket.init('pgsx5s/ono-pan');</script>
  </head>

  <% if store_signed_in? %>
    <body class="hold-transition skin-blue sidebar-mini">
      <div class="wrapper">
        <%= render 'shared/layout/header' %>
        <%= render 'shared/layout/sidebar' %>
        <%= render 'shared/layout/menu' %>
        <div class="content-wrapper bg_image">
          <div class="bg_mask">
            <div class="content">
              <%= yield %>
            </div>
          </div>
        </div>
        <%= render 'shared/layout/footer' %>
      </div>
    </body>
  <% else %>
    <body class="bg_image_login">
      <div class="bg_mask">
        <div class="login-box">
          <div class="login-logo">
            'ono pan
          </div>
          <% if notice %>
            <p class="alert alert-notice"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-error"><%= alert %></p>
          <% end %>
          <div class="card form_frame" style="background: #EBDCB2;">
            <div class="card-body login-card-body">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </body>
  <% end %>
</html>

app/views/shared/layout/_footer.html.erb
<footer class="main-footer">
  <div class="hidden-xs">
    Production by Noriya Saeki
  </div>
</footer>

app/views/shared/layout/_header.html.erb
<header class="main-header">
  <a href="/" class="logo">
    <span class="logo-lg"><b>'ono pan</b></span>
  </a>
  <nav class="navbar navbar-static-top" role="navigation">
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li>
          <!-- TODO:右上のメニューボタンを素早く2回押すと、メニュー中身がdisplay: none;になったままになる -->
          <a href="#" data-toggle="control-sidebar"><i class="fa fa-th-large"></i></a>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/layout/_menu.html.erb
<aside class="control-sidebar control-sidebar-dark">
  <div class="tab-content">
    <p><%= link_to 'プロフィール', store_path(current_store.id) %></p>
    <p><%= link_to 'ログアウト', destroy_store_session_path, method: :delete %></p>
  </div>
</aside>

app/views/shared/layout/_sidebar.html.erb
  <aside class="main-sidebar">
    <section class="sidebar">
      <div class="user-panel">
        <div class="pull-left store_info">
          <p><%= image_tag(@store.image.url, :size => "200x150") %></p>
          <p><%= @store.name %></p>
        </div>
      </div>

      <!-- いらなければ削除予定 -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
            <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
        </div>
      </form>

      <ul class="sidebar-menu">
        <!-- 操作しているページをclass="active"に変化させる -->
        <!-- <li class="active"><a href="#"><i class="fa fa-link"></i> <span>Link</span></a></li> -->

        <li><a href="/products"><i class="fa fa-cutlery"></i><span>商品管理</span></a></li>
        <li><a href="/order_slips"><i class="fa fa-file-text-o"></i><span>注文伝票</span><span class='badge order_badge'><%= @number_purchases_count %></span></a></li>
        <li><a href="/number_purchases"><i class="fa fa-book"></i><span>過去売上伝票</span></a></li>
        <li><a href="/user_info"><i class="fa fa-users"></i><span>顧客情報</span></a></li>
        <li><a href="#"><i class="fa fa-pie-chart"></i><span>顧客分析</span></a></li>
      </ul>
    </section>
  </aside>